remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Bird Recognizer
description: An image classification API that classifies 20 different types of birds around the world

author:
  name: Mohammad Faiyaz Uz Zaman
